### ISSUE TITLE
Consider hosting on Netlify or Vercel

### ISSUE THREAD

**Issue by benmccann** [pocketbase/site#8]
I wanted to let you know that pocketbase is now featured on the homepage of https://kit.svelte.dev/ !

One last thing I noticed while checking out the site is that it gives a pretty good Page Speed Score, but I think it could score even higher by changing hosts. It looks like right now you use Hetzner and the site has to travel across the ocean to get to the Google data center. If you use `@sveltejs/adapter-netlify` or `@sveltejs/adapter-vercel` then the site will be globally distributed and I believe both are free for smaller projects. Hopefully all you'd have to do is create an account, install the adapter, and switch over the DNS.

Sorry for the unsolicited feedback! Please feel free to close this if it's not a priority. I thought I'd share as we'd love to see the sites we're featuring be super fast, but I also totally understand if it's not something you want to invest in

**Comment by ganigeorgiev** [comment]
Thank you for the the feedback and for featuring PocketBase.

I've considered Vercel in the past but for now it is easier for me to maintain and deploy it as it is, because the site is embedded inside the PocketBase live demo application (aka. a PocketBase app binary contains and serves the website).

As mentioned previously, a lot of optimizations could be done. We don't even use a CDN. The server is a small Hetzner CX21 instance with just the binary inside it and a cron job that resets the demo `pb_data` directory every hour.

Once we managed to finalize most of the the piled tasks from the [roadmap](https://github.com/orgs/pocketbase/projects/2), I'll consider further optimizing the website, but this remains a very low priority.

**Comment by Nikhil1920** [comment]
The quickest way to speed up the site is by using cloudflare with cache everything page rule or 

you can move the demo pocketbase instance to a subdomain and just update the iframe url this way the site will be completely static and can be easily moved to static hosts

**Comment by Nikhil1920** [comment]
github pages is also a really good option I can even add the action to deploy automatically

**Comment by ganigeorgiev** [comment]
@Nikhil1920 Thank you for the suggestion but for now let's leave it as it is. It is easier for me to maintain it if the site is part of the binary. We may change it in the future if people complain too much about the loading speed but I think it is acceptable/good-enough at the moment.
